### ISSUE TITLE
Readme has no example code

### ISSUE THREAD

**Issue by schoekek** [TrullJ/ssllabs#1]
Hi Jonathan,

can you insert any example for use the python library in python code?

thx Karsten

**Comment by TrullJ** [comment]
Yes, working on this over the next few days.

**Comment by DragonRebo0rn** [comment]
Hi Jonathan,

Were you ever able to get any sample code together? I'm very interested in how to use this module.

Thanks,

**Comment by TrullJ** [comment]
Take a look.  I still need to add some additional documentation but it should get you started.

**Comment by TrullJ** [comment]
Take a peak now. Just updated how to use the module.  Interested in your feedback.
